### ISSUE TITLE
How to remove or change the Title and Meta Description

### ISSUE THREAD

**Issue by khalidrizwaan** [stormuk/wp-comments-page#2]
Hi

Its a wonderful script.

As per the SEO, new dynamic comments page will have the same "Title" and "Meta Description".

please suggest the solution. 

Thanks
Khalid Rizwan

**Comment by barrywoolgar** [comment]
Hello. This code only rewrites the title (in the function `comments_endpoint_wp_title(...)`), so if it is also being used for the meta description, then this is happening outside of this plugin. Perhaps it's another plugin doing this, or a change to WordPress's behaviour since this plugin was written ~10 years ago.

**Comment by khalidrizwaan** [comment]
Thanks 

can u help me to fix this issue. Please provide your email id so  we can discuss the requirements. We are ready to pay.

Thanks
Khalid Rizwan

**Comment by barrywoolgar** [comment]
Unfortunately we're not in a position to take on that kind of work at the moment. All I can suggest is that you may want to look at where `wp_title` is being used in your templates, or the documentation of any SEO plugin you may be running.

Good luck!

**Comment by khalidrizwaan** [comment]
Thanks,
We are using yoast seo Plugin
Thanks

**Comment by barrywoolgar** [comment]
Just to confirm, this isn't something I can help you with, sorry. Yoast is a well-known plugin though, so hopefully you won't have too much trouble find documentation to help you further.
